name: Movietips
description: A movie list project with tips

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  http: ^0.13.4
  url_launcher: ^6.1.2
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "laucher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
