// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA23uUdLJlwdfVo_sZNl3jMuy3qEwX-Dx0',
    appId: '1:1034836315663:web:7e5de9ff6aad5cef939d7a',
    messagingSenderId: '1034836315663',
    projectId: 'movietipsusers',
    authDomain: 'movietipsusers.firebaseapp.com',
    storageBucket: 'movietipsusers.appspot.com',
    measurementId: 'G-QV1E3RBT4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrnBrc9kCTWtF1kZmH8GpCvjAI4-iVPtI',
    appId: '1:1034836315663:android:10b6d4974dc25c15939d7a',
    messagingSenderId: '1034836315663',
    projectId: 'movietipsusers',
    storageBucket: 'movietipsusers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACICFCOu3XyRHuwBFvVjFFP-EKhmJO_d4',
    appId: '1:1034836315663:ios:e176e1f6e2fef740939d7a',
    messagingSenderId: '1034836315663',
    projectId: 'movietipsusers',
    storageBucket: 'movietipsusers.appspot.com',
    iosClientId: '1034836315663-e4qpjuoqrvheo4r6apte0fu6rl1pce30.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietipsflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACICFCOu3XyRHuwBFvVjFFP-EKhmJO_d4',
    appId: '1:1034836315663:ios:e176e1f6e2fef740939d7a',
    messagingSenderId: '1034836315663',
    projectId: 'movietipsusers',
    storageBucket: 'movietipsusers.appspot.com',
    iosClientId: '1034836315663-e4qpjuoqrvheo4r6apte0fu6rl1pce30.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietipsflutter',
  );
}
